### ISSUE TITLE
Watch video about constants

### ISSUE THREAD

**Issue by mayisa87** [dccl90/TileCostCalculator#1]
https://github.com/dccl90/TileCostCalculator/blob/2cf0a8cd0f6567402b5668dedd9a70e8a030602f/Program.cs#L14

In Module 2 you will learn about constants, if video is already unlocked to you, you can find it here: https://course.raketementoring.com/courses/rakete-mentoring/lectures/46714297

Constants are used to define values, that are fixed and can and should  never be changed later on in your code. 

So your labourRate could be a constant. Constants are always named in UPPER_CASE_LETTERS

so in this case you could define:
const double LABOUR_RATE = 86.00;

**Comment by dccl90** [comment]
Changed to constant.
