### ISSUE TITLE
Calculation of labourCost needs sqFt per hour value

### ISSUE THREAD

**Issue by mayisa87** [dccl90/TileCostCalculator#2]
https://github.com/dccl90/TileCostCalculator/blob/2cf0a8cd0f6567402b5668dedd9a70e8a030602f/Program.cs#L25

If you have a look to the exercise description you will see, that the exact calculation of labour costs requires to take into consideration, how man square feet per hour (20) can be done.

**Comment by dccl90** [comment]
Fixed calculation: area / 20 * LABOUR_RATE
