### ISSUE TITLE
Re-Watch video about nullable warnings

### ISSUE THREAD

**Issue by mayisa87** [dccl90/TileCostCalculator#4]
![image](https://github.com/dccl90/TileCostCalculator/assets/130921606/3b0e4b46-4b85-447e-b64d-9449fbbd65a3)

You may recognized that some of your lines are always marked with this light green lines. There is a video about, how to get rid of them :)

Please do the changes like mentioned in the video. If something is unclear, please come back to ous with the exact timestamp in video that makes you struggle

https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560433

**Comment by dccl90** [comment]
Made necessary change to remove nullable warnings
