### ISSUE TITLE
Do only once

### ISSUE THREAD

**Issue by mayisa87** [dccl90/TileCostCalculator#7]
https://github.com/dccl90/TileCostCalculator/blob/804cf6f4ed98af0459b89363aa64374396ea2012/Program.cs#L34

https://github.com/dccl90/TileCostCalculator/blob/804cf6f4ed98af0459b89363aa64374396ea2012/Program.cs#L40

This code is duplicated and done twice. Better read the user input for cost per unit only once before your if statement.

**Comment by dccl90** [comment]
Removed duplicate code
